/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author BRIANNA
 */
public class ViewMenu extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public ViewMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        
        menuPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Maintenance = new javax.swing.JButton();
        Create = new javax.swing.JButton();
        Features = new javax.swing.JButton();
        Menu = new javax.swing.JLabel();

        menuPanel.setEnabled(false);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(231, 245, 252));
        setBounds(new java.awt.Rectangle(0, 0, 477, 310));

        Maintenance.setBackground(new java.awt.Color(140, 133, 245));
        Maintenance.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        Maintenance.setForeground(new java.awt.Color(255, 255, 255));
        Maintenance.setText("Maintenance Features");
        Maintenance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Maintenance.setBorderPainted(false);
        Maintenance.setFocusable(false);
        Maintenance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Maintenance.setPreferredSize(new java.awt.Dimension(255, 42));

        Create.setBackground(new java.awt.Color(140, 133, 245));
        Create.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        Create.setForeground(new java.awt.Color(255, 255, 255));
        Create.setText("Create Vending Machine");
        Create.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Create.setBorderPainted(false);
        Create.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Create.setFocusable(false);
        Create.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Create.setPreferredSize(new java.awt.Dimension(255, 42));

        Features.setBackground(new java.awt.Color(140, 133, 245));
        Features.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        Features.setForeground(new java.awt.Color(255, 255, 255));
        Features.setText("Vending Features");
        Features.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Features.setBorderPainted(false);
        Features.setFocusable(false);
        Features.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Features.setPreferredSize(new java.awt.Dimension(255, 42));

        Menu.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        Menu.setForeground(new java.awt.Color(215, 92, 181));
        Menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu.setText("MENU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Create, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(Features, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(Maintenance, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Create, Features, Maintenance});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Maintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Features, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Create, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Create, Features, Maintenance});

        pack();
    }// </editor-fold>
    
    public void setMaintenanceBtn(ActionListener e){
        Maintenance.addActionListener(e);
    }

    public void setCreateBtn(ActionListener e){
        Create.addActionListener(e);
    }

    public void setFeaturesBtn(ActionListener e){
        Features.addActionListener(e);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Create;
    private javax.swing.JButton Features;
    private javax.swing.JButton Maintenance;
    private javax.swing.JLabel Menu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration                   
}
