
import java.awt.event.ActionListener;

/**
 * Create menu class
 */

public class CreateMenu extends javax.swing.JFrame {

    /**
     * Creates new form CreateMenu
     */
    public CreateMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    
    /**
     * Initializes all components
     */
    
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        optionLabel = new javax.swing.JLabel();
        regular = new javax.swing.JButton();
        special = new javax.swing.JButton();
        bottom = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        top = new javax.swing.JPanel();
        inputLabel = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        errMessage = new javax.swing.JLabel();
        RVMName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 381, 167));
        setResizable(false);

        optionLabel.setText("Choose type of vending machine");
        optionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        regular.setText("Regular");
        regular.setFocusable(false);
        regular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        special.setText("Special");
        special.setFocusable(false);
        special.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(special)
                .addContainerGap())
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionLabel)
                    .addComponent(regular)
                    .addComponent(special))
                .addContainerGap())
        );

        bottom.setMaximumSize(new java.awt.Dimension(90, 90));
        bottom.setMinimumSize(new java.awt.Dimension(90, 90));

        back.setText("Back");
        back.setFocusable(false);

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputLabel.setText("Input Name:");

        submit.setText("Submit");
        submit.setFocusable(false);

        errMessage.setText("Name is too long! Try again.");

        RVMName.setName(""); // NOI18N

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errMessage)
                    .addGroup(topLayout.createSequentialGroup()
                        .addComponent(RVMName, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLabel)
                    .addComponent(submit)
                    .addComponent(RVMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bottom, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    /**
     * Sets action listener
     * @param e actionlistener object
     */

    public void setBack(ActionListener e) {
        back.addActionListener(e);
    }

    /**
     * Sets action listener
     * @param e actionlistener object
     */

    public void setRegularBtn(ActionListener e) {
        regular.addActionListener(e);
    }

    /**
     * Sets action listener
     * @param e actionlistener object
     */

    public void setSpecBtn(ActionListener e) {
        special.addActionListener(e);
    }

    /**
     * Sets action listener
     * @param e actionlistener object
     */

    public void setSubmitBtn(ActionListener e){
        submit.addActionListener(e);
    }

    /**
     * Hides all option components
     */

    public void hideOptions(){
        regular.setVisible(false);
        special.setVisible(false);
        optionLabel.setVisible(false);
    }

    /**
     * Shows all option components
     */

    public void showOptions(){
        regular.setVisible(true);
        special.setVisible(true);
        optionLabel.setVisible(true);
    }

    /**
     * Gets name input from text field
     */

    public String getName(){
        return RVMName.getText();
    }

    /**
     * Sets error message
     * @param err message to be displayed
     */

    public void setErrMsg(String err){
        errMessage.setVisible(true);
        errMessage.setText(err);
    }

    /**
     * Hides error message
     */

    public void hideErrMsg(){
        errMessage.setVisible(false);
    }

    /**
     * Resets text field for vending machine name
     */

    public void resetTextField(){
        RVMName.setText("");
    }

    /**
     * Sets added vending machine message
     * @param name name of vending machine
     * @param type type of vending machine
     */

    public void setMessage(String name, String type){
        if(name.length() > 10){
            name = name.substring(0, 10);
        }
        message.setText(name + " has been added as " + type);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField RVMName;
    private javax.swing.JButton back;
    private javax.swing.JPanel bottom;
    private javax.swing.JLabel errMessage;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JLabel message;
    private javax.swing.JLabel optionLabel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JButton regular;
    private javax.swing.JButton special;
    private javax.swing.JButton submit;
    private javax.swing.JPanel top;
    // End of variables declaration
}
